// Builders for ChatGPT's 2026-09 transcript DOM (the unit DOM, live 1.1.41): see chatgpt-unit-dom.e2e.mjs.
export const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');
const SR='position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap';
/** A sent file's card, as the unit DOM shows it: a named button over the titled name and its type. */
export const unitCard=name=>`<span class="flex max-w-full flex-col"><span class="group/resource-card relative"><button aria-busy="false" aria-label="${name}" type="button" class="absolute inset-0"></button><span class="flex min-w-0 items-center gap-2 p-2.5"><span><svg aria-hidden="true" style="width:20px;height:20px"></svg></span><span class="flex min-w-0 flex-col"><span title="${name}" class="truncate">${name}</span><span class="truncate">문서</span></span></span></span></span>`;
/** A user unit in its turn container (`files`: the cards before the bubble); the assistant block and
 * the turn's actions are added into the same container later (unitAnswer). */
export const unitTurn=({turn=0,id='user-A',text,files=[]})=>`<div data-turn-key="${id}"><div data-content-search-turn-key="fallback-turn-${turn}"><div class="contents"><div class="contents"><div class="group flex flex-col pb-2 pt-2"><div class="flex flex-col gap-3" data-fixture-blocks><div class="block"><h4 class="sr-only m-0 select-none" style="${SR}">내가 한 말:</h4><div data-chatgpt-search-unit-key="fallback-turn-${turn}:0:user" data-chatgpt-search-message-ids="${id}" class="flex flex-col items-end gap-2">${files.length?`<div class="flex w-full flex-wrap justify-end gap-2">${files.map(unitCard).join('')}</div>`:''}<div data-content-search-unit-key="fallback-turn-${turn}:0:user" class="w-full"><div class="group/user-message flex w-full flex-col items-end gap-1"><div data-user-message-bubble="true" class="bg-user-message relative"><svg aria-hidden="true" style="position:absolute;inset:0"></svg><div class="flex flex-col items-end gap-1"><div class="relative w-full min-w-0"><div class="overflow-hidden" data-search-result-target=""><div><div class="text-size-chat whitespace-pre-wrap" dir="auto">${esc(text)}</div></div></div><span aria-hidden="true">…</span></div><button type="button" aria-expanded="false" data-thread-find-skip="true"><span>더 보기</span></button></div></div><div class="flex flex-row-reverse items-center gap-1"><div class="me-1 ms-1 flex items-center gap-2 opacity-0"><div class="flex turn-action-controls items-center gap-0.5"><span class="contents"><button type="button" aria-label="메시지 복사">c</button></span><span class="contents"><button type="button" aria-label="메시지 편집">e</button></span></div></div></div></div></div></div></div></div></div></div></div></div></div>`;
const BTN='style="display:inline-block;width:32px;height:32px"';
/** The assistant block (its unit, the fenced code block holding `code`) and, when `done`, the turn's
 * action row, rendered into the turn container of user turn `turn`. `ids`: its search message ids. */
export const unitAnswer=({turn=0,id='answer-A',code,ids=`${id} ${id}`,prose=''})=>({
 block:`<div class="block"><span hidden="" data-chatgpt-agent-turn-start=""></span><div data-content-search-unit-key="fallback-turn-${turn}:2:assistant" data-chatgpt-search-unit-key="fallback-turn-${turn}:2:assistant"${ids?` data-chatgpt-search-message-ids="${ids}"`:''}><h4 data-conversation-role="assistant" tabindex="-1" class="sr-only m-0 select-none" style="${SR}">ChatGPT 답변:</h4><div data-chatgpt-selection-conversation-id="local-chatgpt:fixture" data-chatgpt-selection-message-id="${id}" class="group flex min-w-0 flex-col"><div dir="auto" data-markdown-text-style="assistant-message">${prose?`<p>${esc(prose)}</p>`:''}<div class="CodeBlock"><div data-markdown-copy="code-block" data-search-result-target=""><div data-markdown-copy="exclude"><svg aria-hidden="true"></svg><div id="lang">JSON</div><div><span class="contents"><button type="button" aria-label="자동 줄 바꿈 사용" aria-pressed="false">w</button></span><span class="contents"><button type="button" aria-label="복사">c</button></span></div></div><div><div><div dir="ltr"><div><pre><code id="code"><span>${esc(code)}</span></code></pre></div></div></div></div><button aria-hidden="true" aria-label="맨 아래로 스크롤" tabindex="-1" type="button">v</button></div></div></div></div></div></div>`,
 actions:`<div class="mt-1.5 flex turn-action-controls min-h-5"><div class="flex min-h-5 flex-wrap items-center gap-0.5"><span class="contents"><button type="button" aria-label="복사" ${BTN}>c</button></span><span class="contents"><button type="button" aria-label="응답 평가" ${BTN}>r</button></span><span class="contents"><button type="button" aria-label="소리 내어 읽기" aria-pressed="false" ${BTN}>s</button></span><button type="button" aria-label="응답 다시 생성" ${BTN}>g</button></div></div>`,
});
/** In the page: render answer `a` (unitAnswer) into user turn `turn`'s container. */
export const renderUnitAnswer=(page,a,{turn=0,done=true}={})=>page.evaluate(({a,turn,done})=>{
 const box=document.querySelector(`[data-content-search-turn-key="fallback-turn-${turn}"] [data-fixture-blocks]`);
 box.insertAdjacentHTML('beforeend',a.block);if(done)box.insertAdjacentHTML('afterend',a.actions);
},{a,turn,done});

