/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiBridgeRouteImport } from './routes/api/bridge'
import { Route as ApiBridgePackRouteImport } from './routes/api/bridge-pack'
import { Route as ApiHarborRouteImport } from './routes/api/harbor'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeRoute = ApiBridgeRouteImport.update({
  id: '/api/bridge',
  path: '/api/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgePackRoute = ApiBridgePackRouteImport.update({
  id: '/api/bridge-pack',
  path: '/api/bridge-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHarborRoute = ApiHarborRouteImport.update({
  id: '/api/harbor',
  path: '/api/harbor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/api/bridge': typeof ApiBridgeRoute
  '/api/bridge-pack': typeof ApiBridgePackRoute
  '/api/harbor': typeof ApiHarborRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/api/bridge': typeof ApiBridgeRoute
  '/api/bridge-pack': typeof ApiBridgePackRoute
  '/api/harbor': typeof ApiHarborRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/api/bridge': typeof ApiBridgeRoute
  '/api/bridge-pack': typeof ApiBridgePackRoute
  '/api/harbor': typeof ApiHarborRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/playground'
    | '/policies'
    | '/reviews'
    | '/settings'
    | '/api/bridge'
    | '/api/bridge-pack'
    | '/api/harbor'
    | '/api/webhook'
    | '/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/playground'
    | '/policies'
    | '/reviews'
    | '/settings'
    | '/api/bridge'
    | '/api/bridge-pack'
    | '/api/harbor'
    | '/api/webhook'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/playground'
    | '/policies'
    | '/reviews'
    | '/settings'
    | '/api/bridge'
    | '/api/bridge-pack'
    | '/api/harbor'
    | '/api/webhook'
    | '/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoliciesRoute: typeof PoliciesRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  ApiBridgeRoute: typeof ApiBridgeRoute
  ApiBridgePackRoute: typeof ApiBridgePackRoute
  ApiHarborRoute: typeof ApiHarborRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  JobsIdRoute: typeof JobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge': {
      id: '/api/bridge'
      path: '/api/bridge'
      fullPath: '/api/bridge'
      preLoaderRoute: typeof ApiBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge-pack': {
      id: '/api/bridge-pack'
      path: '/api/bridge-pack'
      fullPath: '/api/bridge-pack'
      preLoaderRoute: typeof ApiBridgePackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/harbor': {
      id: '/api/harbor'
      path: '/api/harbor'
      fullPath: '/api/harbor'
      preLoaderRoute: typeof ApiHarborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoliciesRoute: PoliciesRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  ApiBridgeRoute: ApiBridgeRoute,
  ApiBridgePackRoute: ApiBridgePackRoute,
  ApiHarborRoute: ApiHarborRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  JobsIdRoute: JobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
